name: Build Pico Roland Mouse

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: sudo apt update && sudo apt install -y cmake gcc-arm-none-eabi build-essential git

      - name: Clone Pico SDK
        run: |
          git clone --depth 1 https://github.com/raspberrypi/pico-sdk.git
          git submodule update --init

      - name: Configure & Build
        run: |
          export PICO_SDK_PATH=$PWD/pico-sdk
          mkdir build && cd build
          cmake ..
          make -j$(nproc)

      - name: Upload Firmware
        uses: actions/upload-artifact@v4
        with:
          name: pico_roland_mouse.uf2
          path: build/*.uf2
