name: Build Pico Roland Mouse

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Build Tools
        run: |
          sudo apt update
          sudo apt install -y cmake gcc-arm-none-eabi build-essential git

      - name: Clone Pico SDK + TinyUSB
        run: |
          git clone --recurse-submodules --depth 1 https://github.com/raspberrypi/pico-sdk.git
          export PICO_SDK_PATH=$PWD/pico-sdk
          mkdir build && cd build
          cmake -DPICO_SDK_PATH=$PICO_SDK_PATH ..
          make -j$(nproc)

      - name: Upload Firmware
        uses: actions/upload-artifact@v4
        with:
          name: pico_roland_mouse.uf2
          path: build/*.uf2
